// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axrrpvgecbxiypsxklbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4cnJwdmdlY2J4aXlwc3hrbGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTA0OTQsImV4cCI6MjA2MDI4NjQ5NH0.4bqLkUVlrInfJj8kWB_8BwrsKe9OLYJAy3ryYqLAZqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});