// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xksmyzjqrdpjclkisiir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrc215empxcmRwamNsa2lzaWlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDA5MDgsImV4cCI6MjA2OTM3NjkwOH0.92_K0Ewgti02YZ6VR_zOKacvIojFLtWoq4K88ClEJHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});